use poc_typeinfo_new_deser::{Ser, json::JsonSerializer};

macro_rules! def_struct {
    ($name:ident) => {
        #[allow(dead_code)]
        struct $name {
            a: u32,
            b: i64,
            c: f64,
            d: bool,
            e: String,
            f: Option<u32>,
            g: Vec<String>,
            h: (u32, u64),
        }
        impl $name {
            fn sample() -> Self {
                Self {
                    a: 1,
                    b: 2,
                    c: 3.0,
                    d: true,
                    e: String::from("x"),
                    f: Some(7),
                    g: vec![String::from("y")],
                    h: (1, 2),
                }
            }
        }
    };
}

def_struct!(S000);
def_struct!(S001);
def_struct!(S002);
def_struct!(S003);
def_struct!(S004);
def_struct!(S005);
def_struct!(S006);
def_struct!(S007);
def_struct!(S008);
def_struct!(S009);
def_struct!(S010);
def_struct!(S011);
def_struct!(S012);
def_struct!(S013);
def_struct!(S014);
def_struct!(S015);
def_struct!(S016);
def_struct!(S017);
def_struct!(S018);
def_struct!(S019);
def_struct!(S020);
def_struct!(S021);
def_struct!(S022);
def_struct!(S023);
def_struct!(S024);
def_struct!(S025);
def_struct!(S026);
def_struct!(S027);
def_struct!(S028);
def_struct!(S029);
def_struct!(S030);
def_struct!(S031);
def_struct!(S032);
def_struct!(S033);
def_struct!(S034);
def_struct!(S035);
def_struct!(S036);
def_struct!(S037);
def_struct!(S038);
def_struct!(S039);
def_struct!(S040);
def_struct!(S041);
def_struct!(S042);
def_struct!(S043);
def_struct!(S044);
def_struct!(S045);
def_struct!(S046);
def_struct!(S047);
def_struct!(S048);
def_struct!(S049);
def_struct!(S050);
def_struct!(S051);
def_struct!(S052);
def_struct!(S053);
def_struct!(S054);
def_struct!(S055);
def_struct!(S056);
def_struct!(S057);
def_struct!(S058);
def_struct!(S059);
def_struct!(S060);
def_struct!(S061);
def_struct!(S062);
def_struct!(S063);
def_struct!(S064);
def_struct!(S065);
def_struct!(S066);
def_struct!(S067);
def_struct!(S068);
def_struct!(S069);
def_struct!(S070);
def_struct!(S071);
def_struct!(S072);
def_struct!(S073);
def_struct!(S074);
def_struct!(S075);
def_struct!(S076);
def_struct!(S077);
def_struct!(S078);
def_struct!(S079);
def_struct!(S080);
def_struct!(S081);
def_struct!(S082);
def_struct!(S083);
def_struct!(S084);
def_struct!(S085);
def_struct!(S086);
def_struct!(S087);
def_struct!(S088);
def_struct!(S089);
def_struct!(S090);
def_struct!(S091);
def_struct!(S092);
def_struct!(S093);
def_struct!(S094);
def_struct!(S095);
def_struct!(S096);
def_struct!(S097);
def_struct!(S098);
def_struct!(S099);
def_struct!(S100);
def_struct!(S101);
def_struct!(S102);
def_struct!(S103);
def_struct!(S104);
def_struct!(S105);
def_struct!(S106);
def_struct!(S107);
def_struct!(S108);
def_struct!(S109);
def_struct!(S110);
def_struct!(S111);
def_struct!(S112);
def_struct!(S113);
def_struct!(S114);
def_struct!(S115);
def_struct!(S116);
def_struct!(S117);
def_struct!(S118);
def_struct!(S119);
def_struct!(S120);
def_struct!(S121);
def_struct!(S122);
def_struct!(S123);
def_struct!(S124);
def_struct!(S125);
def_struct!(S126);
def_struct!(S127);
def_struct!(S128);
def_struct!(S129);
def_struct!(S130);
def_struct!(S131);
def_struct!(S132);
def_struct!(S133);
def_struct!(S134);
def_struct!(S135);
def_struct!(S136);
def_struct!(S137);
def_struct!(S138);
def_struct!(S139);
def_struct!(S140);
def_struct!(S141);
def_struct!(S142);
def_struct!(S143);
def_struct!(S144);
def_struct!(S145);
def_struct!(S146);
def_struct!(S147);
def_struct!(S148);
def_struct!(S149);
def_struct!(S150);
def_struct!(S151);
def_struct!(S152);
def_struct!(S153);
def_struct!(S154);
def_struct!(S155);
def_struct!(S156);
def_struct!(S157);
def_struct!(S158);
def_struct!(S159);
def_struct!(S160);
def_struct!(S161);
def_struct!(S162);
def_struct!(S163);
def_struct!(S164);
def_struct!(S165);
def_struct!(S166);
def_struct!(S167);
def_struct!(S168);
def_struct!(S169);
def_struct!(S170);
def_struct!(S171);
def_struct!(S172);
def_struct!(S173);
def_struct!(S174);
def_struct!(S175);
def_struct!(S176);
def_struct!(S177);
def_struct!(S178);
def_struct!(S179);
def_struct!(S180);
def_struct!(S181);
def_struct!(S182);
def_struct!(S183);
def_struct!(S184);
def_struct!(S185);
def_struct!(S186);
def_struct!(S187);
def_struct!(S188);
def_struct!(S189);
def_struct!(S190);
def_struct!(S191);
def_struct!(S192);
def_struct!(S193);
def_struct!(S194);
def_struct!(S195);
def_struct!(S196);
def_struct!(S197);
def_struct!(S198);
def_struct!(S199);

fn main() {
    let mut ser = JsonSerializer::new_vec();
    S000::sample().serialize(&mut ser).unwrap();
    S001::sample().serialize(&mut ser).unwrap();
    S002::sample().serialize(&mut ser).unwrap();
    S003::sample().serialize(&mut ser).unwrap();
    S004::sample().serialize(&mut ser).unwrap();
    S005::sample().serialize(&mut ser).unwrap();
    S006::sample().serialize(&mut ser).unwrap();
    S007::sample().serialize(&mut ser).unwrap();
    S008::sample().serialize(&mut ser).unwrap();
    S009::sample().serialize(&mut ser).unwrap();
    S010::sample().serialize(&mut ser).unwrap();
    S011::sample().serialize(&mut ser).unwrap();
    S012::sample().serialize(&mut ser).unwrap();
    S013::sample().serialize(&mut ser).unwrap();
    S014::sample().serialize(&mut ser).unwrap();
    S015::sample().serialize(&mut ser).unwrap();
    S016::sample().serialize(&mut ser).unwrap();
    S017::sample().serialize(&mut ser).unwrap();
    S018::sample().serialize(&mut ser).unwrap();
    S019::sample().serialize(&mut ser).unwrap();
    S020::sample().serialize(&mut ser).unwrap();
    S021::sample().serialize(&mut ser).unwrap();
    S022::sample().serialize(&mut ser).unwrap();
    S023::sample().serialize(&mut ser).unwrap();
    S024::sample().serialize(&mut ser).unwrap();
    S025::sample().serialize(&mut ser).unwrap();
    S026::sample().serialize(&mut ser).unwrap();
    S027::sample().serialize(&mut ser).unwrap();
    S028::sample().serialize(&mut ser).unwrap();
    S029::sample().serialize(&mut ser).unwrap();
    S030::sample().serialize(&mut ser).unwrap();
    S031::sample().serialize(&mut ser).unwrap();
    S032::sample().serialize(&mut ser).unwrap();
    S033::sample().serialize(&mut ser).unwrap();
    S034::sample().serialize(&mut ser).unwrap();
    S035::sample().serialize(&mut ser).unwrap();
    S036::sample().serialize(&mut ser).unwrap();
    S037::sample().serialize(&mut ser).unwrap();
    S038::sample().serialize(&mut ser).unwrap();
    S039::sample().serialize(&mut ser).unwrap();
    S040::sample().serialize(&mut ser).unwrap();
    S041::sample().serialize(&mut ser).unwrap();
    S042::sample().serialize(&mut ser).unwrap();
    S043::sample().serialize(&mut ser).unwrap();
    S044::sample().serialize(&mut ser).unwrap();
    S045::sample().serialize(&mut ser).unwrap();
    S046::sample().serialize(&mut ser).unwrap();
    S047::sample().serialize(&mut ser).unwrap();
    S048::sample().serialize(&mut ser).unwrap();
    S049::sample().serialize(&mut ser).unwrap();
    S050::sample().serialize(&mut ser).unwrap();
    S051::sample().serialize(&mut ser).unwrap();
    S052::sample().serialize(&mut ser).unwrap();
    S053::sample().serialize(&mut ser).unwrap();
    S054::sample().serialize(&mut ser).unwrap();
    S055::sample().serialize(&mut ser).unwrap();
    S056::sample().serialize(&mut ser).unwrap();
    S057::sample().serialize(&mut ser).unwrap();
    S058::sample().serialize(&mut ser).unwrap();
    S059::sample().serialize(&mut ser).unwrap();
    S060::sample().serialize(&mut ser).unwrap();
    S061::sample().serialize(&mut ser).unwrap();
    S062::sample().serialize(&mut ser).unwrap();
    S063::sample().serialize(&mut ser).unwrap();
    S064::sample().serialize(&mut ser).unwrap();
    S065::sample().serialize(&mut ser).unwrap();
    S066::sample().serialize(&mut ser).unwrap();
    S067::sample().serialize(&mut ser).unwrap();
    S068::sample().serialize(&mut ser).unwrap();
    S069::sample().serialize(&mut ser).unwrap();
    S070::sample().serialize(&mut ser).unwrap();
    S071::sample().serialize(&mut ser).unwrap();
    S072::sample().serialize(&mut ser).unwrap();
    S073::sample().serialize(&mut ser).unwrap();
    S074::sample().serialize(&mut ser).unwrap();
    S075::sample().serialize(&mut ser).unwrap();
    S076::sample().serialize(&mut ser).unwrap();
    S077::sample().serialize(&mut ser).unwrap();
    S078::sample().serialize(&mut ser).unwrap();
    S079::sample().serialize(&mut ser).unwrap();
    S080::sample().serialize(&mut ser).unwrap();
    S081::sample().serialize(&mut ser).unwrap();
    S082::sample().serialize(&mut ser).unwrap();
    S083::sample().serialize(&mut ser).unwrap();
    S084::sample().serialize(&mut ser).unwrap();
    S085::sample().serialize(&mut ser).unwrap();
    S086::sample().serialize(&mut ser).unwrap();
    S087::sample().serialize(&mut ser).unwrap();
    S088::sample().serialize(&mut ser).unwrap();
    S089::sample().serialize(&mut ser).unwrap();
    S090::sample().serialize(&mut ser).unwrap();
    S091::sample().serialize(&mut ser).unwrap();
    S092::sample().serialize(&mut ser).unwrap();
    S093::sample().serialize(&mut ser).unwrap();
    S094::sample().serialize(&mut ser).unwrap();
    S095::sample().serialize(&mut ser).unwrap();
    S096::sample().serialize(&mut ser).unwrap();
    S097::sample().serialize(&mut ser).unwrap();
    S098::sample().serialize(&mut ser).unwrap();
    S099::sample().serialize(&mut ser).unwrap();
    S100::sample().serialize(&mut ser).unwrap();
    S101::sample().serialize(&mut ser).unwrap();
    S102::sample().serialize(&mut ser).unwrap();
    S103::sample().serialize(&mut ser).unwrap();
    S104::sample().serialize(&mut ser).unwrap();
    S105::sample().serialize(&mut ser).unwrap();
    S106::sample().serialize(&mut ser).unwrap();
    S107::sample().serialize(&mut ser).unwrap();
    S108::sample().serialize(&mut ser).unwrap();
    S109::sample().serialize(&mut ser).unwrap();
    S110::sample().serialize(&mut ser).unwrap();
    S111::sample().serialize(&mut ser).unwrap();
    S112::sample().serialize(&mut ser).unwrap();
    S113::sample().serialize(&mut ser).unwrap();
    S114::sample().serialize(&mut ser).unwrap();
    S115::sample().serialize(&mut ser).unwrap();
    S116::sample().serialize(&mut ser).unwrap();
    S117::sample().serialize(&mut ser).unwrap();
    S118::sample().serialize(&mut ser).unwrap();
    S119::sample().serialize(&mut ser).unwrap();
    S120::sample().serialize(&mut ser).unwrap();
    S121::sample().serialize(&mut ser).unwrap();
    S122::sample().serialize(&mut ser).unwrap();
    S123::sample().serialize(&mut ser).unwrap();
    S124::sample().serialize(&mut ser).unwrap();
    S125::sample().serialize(&mut ser).unwrap();
    S126::sample().serialize(&mut ser).unwrap();
    S127::sample().serialize(&mut ser).unwrap();
    S128::sample().serialize(&mut ser).unwrap();
    S129::sample().serialize(&mut ser).unwrap();
    S130::sample().serialize(&mut ser).unwrap();
    S131::sample().serialize(&mut ser).unwrap();
    S132::sample().serialize(&mut ser).unwrap();
    S133::sample().serialize(&mut ser).unwrap();
    S134::sample().serialize(&mut ser).unwrap();
    S135::sample().serialize(&mut ser).unwrap();
    S136::sample().serialize(&mut ser).unwrap();
    S137::sample().serialize(&mut ser).unwrap();
    S138::sample().serialize(&mut ser).unwrap();
    S139::sample().serialize(&mut ser).unwrap();
    S140::sample().serialize(&mut ser).unwrap();
    S141::sample().serialize(&mut ser).unwrap();
    S142::sample().serialize(&mut ser).unwrap();
    S143::sample().serialize(&mut ser).unwrap();
    S144::sample().serialize(&mut ser).unwrap();
    S145::sample().serialize(&mut ser).unwrap();
    S146::sample().serialize(&mut ser).unwrap();
    S147::sample().serialize(&mut ser).unwrap();
    S148::sample().serialize(&mut ser).unwrap();
    S149::sample().serialize(&mut ser).unwrap();
    S150::sample().serialize(&mut ser).unwrap();
    S151::sample().serialize(&mut ser).unwrap();
    S152::sample().serialize(&mut ser).unwrap();
    S153::sample().serialize(&mut ser).unwrap();
    S154::sample().serialize(&mut ser).unwrap();
    S155::sample().serialize(&mut ser).unwrap();
    S156::sample().serialize(&mut ser).unwrap();
    S157::sample().serialize(&mut ser).unwrap();
    S158::sample().serialize(&mut ser).unwrap();
    S159::sample().serialize(&mut ser).unwrap();
    S160::sample().serialize(&mut ser).unwrap();
    S161::sample().serialize(&mut ser).unwrap();
    S162::sample().serialize(&mut ser).unwrap();
    S163::sample().serialize(&mut ser).unwrap();
    S164::sample().serialize(&mut ser).unwrap();
    S165::sample().serialize(&mut ser).unwrap();
    S166::sample().serialize(&mut ser).unwrap();
    S167::sample().serialize(&mut ser).unwrap();
    S168::sample().serialize(&mut ser).unwrap();
    S169::sample().serialize(&mut ser).unwrap();
    S170::sample().serialize(&mut ser).unwrap();
    S171::sample().serialize(&mut ser).unwrap();
    S172::sample().serialize(&mut ser).unwrap();
    S173::sample().serialize(&mut ser).unwrap();
    S174::sample().serialize(&mut ser).unwrap();
    S175::sample().serialize(&mut ser).unwrap();
    S176::sample().serialize(&mut ser).unwrap();
    S177::sample().serialize(&mut ser).unwrap();
    S178::sample().serialize(&mut ser).unwrap();
    S179::sample().serialize(&mut ser).unwrap();
    S180::sample().serialize(&mut ser).unwrap();
    S181::sample().serialize(&mut ser).unwrap();
    S182::sample().serialize(&mut ser).unwrap();
    S183::sample().serialize(&mut ser).unwrap();
    S184::sample().serialize(&mut ser).unwrap();
    S185::sample().serialize(&mut ser).unwrap();
    S186::sample().serialize(&mut ser).unwrap();
    S187::sample().serialize(&mut ser).unwrap();
    S188::sample().serialize(&mut ser).unwrap();
    S189::sample().serialize(&mut ser).unwrap();
    S190::sample().serialize(&mut ser).unwrap();
    S191::sample().serialize(&mut ser).unwrap();
    S192::sample().serialize(&mut ser).unwrap();
    S193::sample().serialize(&mut ser).unwrap();
    S194::sample().serialize(&mut ser).unwrap();
    S195::sample().serialize(&mut ser).unwrap();
    S196::sample().serialize(&mut ser).unwrap();
    S197::sample().serialize(&mut ser).unwrap();
    S198::sample().serialize(&mut ser).unwrap();
    S199::sample().serialize(&mut ser).unwrap();
    std::hint::black_box(ser.into_vec());
}
