use serde::Serialize;
use serde_json::to_writer;

macro_rules! def_struct {
    ($name:ident) => {
        #[allow(dead_code)]
        #[derive(Serialize)]
        struct $name {
            a: u32,
            b: i64,
            c: f64,
            d: bool,
            e: String,
            f: Option<u32>,
            g: Vec<String>,
            h: (u32, u64),
        }
        impl $name {
            fn sample() -> Self {
                Self {
                    a: 1,
                    b: 2,
                    c: 3.0,
                    d: true,
                    e: String::from("x"),
                    f: Some(7),
                    g: vec![String::from("y")],
                    h: (1, 2),
                }
            }
        }
    };
}

def_struct!(S000);
def_struct!(S001);
def_struct!(S002);
def_struct!(S003);
def_struct!(S004);
def_struct!(S005);
def_struct!(S006);
def_struct!(S007);
def_struct!(S008);
def_struct!(S009);
def_struct!(S010);
def_struct!(S011);
def_struct!(S012);
def_struct!(S013);
def_struct!(S014);
def_struct!(S015);
def_struct!(S016);
def_struct!(S017);
def_struct!(S018);
def_struct!(S019);
def_struct!(S020);
def_struct!(S021);
def_struct!(S022);
def_struct!(S023);
def_struct!(S024);
def_struct!(S025);
def_struct!(S026);
def_struct!(S027);
def_struct!(S028);
def_struct!(S029);
def_struct!(S030);
def_struct!(S031);
def_struct!(S032);
def_struct!(S033);
def_struct!(S034);
def_struct!(S035);
def_struct!(S036);
def_struct!(S037);
def_struct!(S038);
def_struct!(S039);
def_struct!(S040);
def_struct!(S041);
def_struct!(S042);
def_struct!(S043);
def_struct!(S044);
def_struct!(S045);
def_struct!(S046);
def_struct!(S047);
def_struct!(S048);
def_struct!(S049);
def_struct!(S050);
def_struct!(S051);
def_struct!(S052);
def_struct!(S053);
def_struct!(S054);
def_struct!(S055);
def_struct!(S056);
def_struct!(S057);
def_struct!(S058);
def_struct!(S059);
def_struct!(S060);
def_struct!(S061);
def_struct!(S062);
def_struct!(S063);
def_struct!(S064);
def_struct!(S065);
def_struct!(S066);
def_struct!(S067);
def_struct!(S068);
def_struct!(S069);
def_struct!(S070);
def_struct!(S071);
def_struct!(S072);
def_struct!(S073);
def_struct!(S074);
def_struct!(S075);
def_struct!(S076);
def_struct!(S077);
def_struct!(S078);
def_struct!(S079);
def_struct!(S080);
def_struct!(S081);
def_struct!(S082);
def_struct!(S083);
def_struct!(S084);
def_struct!(S085);
def_struct!(S086);
def_struct!(S087);
def_struct!(S088);
def_struct!(S089);
def_struct!(S090);
def_struct!(S091);
def_struct!(S092);
def_struct!(S093);
def_struct!(S094);
def_struct!(S095);
def_struct!(S096);
def_struct!(S097);
def_struct!(S098);
def_struct!(S099);
def_struct!(S100);
def_struct!(S101);
def_struct!(S102);
def_struct!(S103);
def_struct!(S104);
def_struct!(S105);
def_struct!(S106);
def_struct!(S107);
def_struct!(S108);
def_struct!(S109);
def_struct!(S110);
def_struct!(S111);
def_struct!(S112);
def_struct!(S113);
def_struct!(S114);
def_struct!(S115);
def_struct!(S116);
def_struct!(S117);
def_struct!(S118);
def_struct!(S119);
def_struct!(S120);
def_struct!(S121);
def_struct!(S122);
def_struct!(S123);
def_struct!(S124);
def_struct!(S125);
def_struct!(S126);
def_struct!(S127);
def_struct!(S128);
def_struct!(S129);
def_struct!(S130);
def_struct!(S131);
def_struct!(S132);
def_struct!(S133);
def_struct!(S134);
def_struct!(S135);
def_struct!(S136);
def_struct!(S137);
def_struct!(S138);
def_struct!(S139);
def_struct!(S140);
def_struct!(S141);
def_struct!(S142);
def_struct!(S143);
def_struct!(S144);
def_struct!(S145);
def_struct!(S146);
def_struct!(S147);
def_struct!(S148);
def_struct!(S149);
def_struct!(S150);
def_struct!(S151);
def_struct!(S152);
def_struct!(S153);
def_struct!(S154);
def_struct!(S155);
def_struct!(S156);
def_struct!(S157);
def_struct!(S158);
def_struct!(S159);
def_struct!(S160);
def_struct!(S161);
def_struct!(S162);
def_struct!(S163);
def_struct!(S164);
def_struct!(S165);
def_struct!(S166);
def_struct!(S167);
def_struct!(S168);
def_struct!(S169);
def_struct!(S170);
def_struct!(S171);
def_struct!(S172);
def_struct!(S173);
def_struct!(S174);
def_struct!(S175);
def_struct!(S176);
def_struct!(S177);
def_struct!(S178);
def_struct!(S179);
def_struct!(S180);
def_struct!(S181);
def_struct!(S182);
def_struct!(S183);
def_struct!(S184);
def_struct!(S185);
def_struct!(S186);
def_struct!(S187);
def_struct!(S188);
def_struct!(S189);
def_struct!(S190);
def_struct!(S191);
def_struct!(S192);
def_struct!(S193);
def_struct!(S194);
def_struct!(S195);
def_struct!(S196);
def_struct!(S197);
def_struct!(S198);
def_struct!(S199);

fn main() {
    let mut buf: Vec<u8> = Vec::new();
    to_writer(&mut buf, &S000::sample()).unwrap();
    to_writer(&mut buf, &S001::sample()).unwrap();
    to_writer(&mut buf, &S002::sample()).unwrap();
    to_writer(&mut buf, &S003::sample()).unwrap();
    to_writer(&mut buf, &S004::sample()).unwrap();
    to_writer(&mut buf, &S005::sample()).unwrap();
    to_writer(&mut buf, &S006::sample()).unwrap();
    to_writer(&mut buf, &S007::sample()).unwrap();
    to_writer(&mut buf, &S008::sample()).unwrap();
    to_writer(&mut buf, &S009::sample()).unwrap();
    to_writer(&mut buf, &S010::sample()).unwrap();
    to_writer(&mut buf, &S011::sample()).unwrap();
    to_writer(&mut buf, &S012::sample()).unwrap();
    to_writer(&mut buf, &S013::sample()).unwrap();
    to_writer(&mut buf, &S014::sample()).unwrap();
    to_writer(&mut buf, &S015::sample()).unwrap();
    to_writer(&mut buf, &S016::sample()).unwrap();
    to_writer(&mut buf, &S017::sample()).unwrap();
    to_writer(&mut buf, &S018::sample()).unwrap();
    to_writer(&mut buf, &S019::sample()).unwrap();
    to_writer(&mut buf, &S020::sample()).unwrap();
    to_writer(&mut buf, &S021::sample()).unwrap();
    to_writer(&mut buf, &S022::sample()).unwrap();
    to_writer(&mut buf, &S023::sample()).unwrap();
    to_writer(&mut buf, &S024::sample()).unwrap();
    to_writer(&mut buf, &S025::sample()).unwrap();
    to_writer(&mut buf, &S026::sample()).unwrap();
    to_writer(&mut buf, &S027::sample()).unwrap();
    to_writer(&mut buf, &S028::sample()).unwrap();
    to_writer(&mut buf, &S029::sample()).unwrap();
    to_writer(&mut buf, &S030::sample()).unwrap();
    to_writer(&mut buf, &S031::sample()).unwrap();
    to_writer(&mut buf, &S032::sample()).unwrap();
    to_writer(&mut buf, &S033::sample()).unwrap();
    to_writer(&mut buf, &S034::sample()).unwrap();
    to_writer(&mut buf, &S035::sample()).unwrap();
    to_writer(&mut buf, &S036::sample()).unwrap();
    to_writer(&mut buf, &S037::sample()).unwrap();
    to_writer(&mut buf, &S038::sample()).unwrap();
    to_writer(&mut buf, &S039::sample()).unwrap();
    to_writer(&mut buf, &S040::sample()).unwrap();
    to_writer(&mut buf, &S041::sample()).unwrap();
    to_writer(&mut buf, &S042::sample()).unwrap();
    to_writer(&mut buf, &S043::sample()).unwrap();
    to_writer(&mut buf, &S044::sample()).unwrap();
    to_writer(&mut buf, &S045::sample()).unwrap();
    to_writer(&mut buf, &S046::sample()).unwrap();
    to_writer(&mut buf, &S047::sample()).unwrap();
    to_writer(&mut buf, &S048::sample()).unwrap();
    to_writer(&mut buf, &S049::sample()).unwrap();
    to_writer(&mut buf, &S050::sample()).unwrap();
    to_writer(&mut buf, &S051::sample()).unwrap();
    to_writer(&mut buf, &S052::sample()).unwrap();
    to_writer(&mut buf, &S053::sample()).unwrap();
    to_writer(&mut buf, &S054::sample()).unwrap();
    to_writer(&mut buf, &S055::sample()).unwrap();
    to_writer(&mut buf, &S056::sample()).unwrap();
    to_writer(&mut buf, &S057::sample()).unwrap();
    to_writer(&mut buf, &S058::sample()).unwrap();
    to_writer(&mut buf, &S059::sample()).unwrap();
    to_writer(&mut buf, &S060::sample()).unwrap();
    to_writer(&mut buf, &S061::sample()).unwrap();
    to_writer(&mut buf, &S062::sample()).unwrap();
    to_writer(&mut buf, &S063::sample()).unwrap();
    to_writer(&mut buf, &S064::sample()).unwrap();
    to_writer(&mut buf, &S065::sample()).unwrap();
    to_writer(&mut buf, &S066::sample()).unwrap();
    to_writer(&mut buf, &S067::sample()).unwrap();
    to_writer(&mut buf, &S068::sample()).unwrap();
    to_writer(&mut buf, &S069::sample()).unwrap();
    to_writer(&mut buf, &S070::sample()).unwrap();
    to_writer(&mut buf, &S071::sample()).unwrap();
    to_writer(&mut buf, &S072::sample()).unwrap();
    to_writer(&mut buf, &S073::sample()).unwrap();
    to_writer(&mut buf, &S074::sample()).unwrap();
    to_writer(&mut buf, &S075::sample()).unwrap();
    to_writer(&mut buf, &S076::sample()).unwrap();
    to_writer(&mut buf, &S077::sample()).unwrap();
    to_writer(&mut buf, &S078::sample()).unwrap();
    to_writer(&mut buf, &S079::sample()).unwrap();
    to_writer(&mut buf, &S080::sample()).unwrap();
    to_writer(&mut buf, &S081::sample()).unwrap();
    to_writer(&mut buf, &S082::sample()).unwrap();
    to_writer(&mut buf, &S083::sample()).unwrap();
    to_writer(&mut buf, &S084::sample()).unwrap();
    to_writer(&mut buf, &S085::sample()).unwrap();
    to_writer(&mut buf, &S086::sample()).unwrap();
    to_writer(&mut buf, &S087::sample()).unwrap();
    to_writer(&mut buf, &S088::sample()).unwrap();
    to_writer(&mut buf, &S089::sample()).unwrap();
    to_writer(&mut buf, &S090::sample()).unwrap();
    to_writer(&mut buf, &S091::sample()).unwrap();
    to_writer(&mut buf, &S092::sample()).unwrap();
    to_writer(&mut buf, &S093::sample()).unwrap();
    to_writer(&mut buf, &S094::sample()).unwrap();
    to_writer(&mut buf, &S095::sample()).unwrap();
    to_writer(&mut buf, &S096::sample()).unwrap();
    to_writer(&mut buf, &S097::sample()).unwrap();
    to_writer(&mut buf, &S098::sample()).unwrap();
    to_writer(&mut buf, &S099::sample()).unwrap();
    to_writer(&mut buf, &S100::sample()).unwrap();
    to_writer(&mut buf, &S101::sample()).unwrap();
    to_writer(&mut buf, &S102::sample()).unwrap();
    to_writer(&mut buf, &S103::sample()).unwrap();
    to_writer(&mut buf, &S104::sample()).unwrap();
    to_writer(&mut buf, &S105::sample()).unwrap();
    to_writer(&mut buf, &S106::sample()).unwrap();
    to_writer(&mut buf, &S107::sample()).unwrap();
    to_writer(&mut buf, &S108::sample()).unwrap();
    to_writer(&mut buf, &S109::sample()).unwrap();
    to_writer(&mut buf, &S110::sample()).unwrap();
    to_writer(&mut buf, &S111::sample()).unwrap();
    to_writer(&mut buf, &S112::sample()).unwrap();
    to_writer(&mut buf, &S113::sample()).unwrap();
    to_writer(&mut buf, &S114::sample()).unwrap();
    to_writer(&mut buf, &S115::sample()).unwrap();
    to_writer(&mut buf, &S116::sample()).unwrap();
    to_writer(&mut buf, &S117::sample()).unwrap();
    to_writer(&mut buf, &S118::sample()).unwrap();
    to_writer(&mut buf, &S119::sample()).unwrap();
    to_writer(&mut buf, &S120::sample()).unwrap();
    to_writer(&mut buf, &S121::sample()).unwrap();
    to_writer(&mut buf, &S122::sample()).unwrap();
    to_writer(&mut buf, &S123::sample()).unwrap();
    to_writer(&mut buf, &S124::sample()).unwrap();
    to_writer(&mut buf, &S125::sample()).unwrap();
    to_writer(&mut buf, &S126::sample()).unwrap();
    to_writer(&mut buf, &S127::sample()).unwrap();
    to_writer(&mut buf, &S128::sample()).unwrap();
    to_writer(&mut buf, &S129::sample()).unwrap();
    to_writer(&mut buf, &S130::sample()).unwrap();
    to_writer(&mut buf, &S131::sample()).unwrap();
    to_writer(&mut buf, &S132::sample()).unwrap();
    to_writer(&mut buf, &S133::sample()).unwrap();
    to_writer(&mut buf, &S134::sample()).unwrap();
    to_writer(&mut buf, &S135::sample()).unwrap();
    to_writer(&mut buf, &S136::sample()).unwrap();
    to_writer(&mut buf, &S137::sample()).unwrap();
    to_writer(&mut buf, &S138::sample()).unwrap();
    to_writer(&mut buf, &S139::sample()).unwrap();
    to_writer(&mut buf, &S140::sample()).unwrap();
    to_writer(&mut buf, &S141::sample()).unwrap();
    to_writer(&mut buf, &S142::sample()).unwrap();
    to_writer(&mut buf, &S143::sample()).unwrap();
    to_writer(&mut buf, &S144::sample()).unwrap();
    to_writer(&mut buf, &S145::sample()).unwrap();
    to_writer(&mut buf, &S146::sample()).unwrap();
    to_writer(&mut buf, &S147::sample()).unwrap();
    to_writer(&mut buf, &S148::sample()).unwrap();
    to_writer(&mut buf, &S149::sample()).unwrap();
    to_writer(&mut buf, &S150::sample()).unwrap();
    to_writer(&mut buf, &S151::sample()).unwrap();
    to_writer(&mut buf, &S152::sample()).unwrap();
    to_writer(&mut buf, &S153::sample()).unwrap();
    to_writer(&mut buf, &S154::sample()).unwrap();
    to_writer(&mut buf, &S155::sample()).unwrap();
    to_writer(&mut buf, &S156::sample()).unwrap();
    to_writer(&mut buf, &S157::sample()).unwrap();
    to_writer(&mut buf, &S158::sample()).unwrap();
    to_writer(&mut buf, &S159::sample()).unwrap();
    to_writer(&mut buf, &S160::sample()).unwrap();
    to_writer(&mut buf, &S161::sample()).unwrap();
    to_writer(&mut buf, &S162::sample()).unwrap();
    to_writer(&mut buf, &S163::sample()).unwrap();
    to_writer(&mut buf, &S164::sample()).unwrap();
    to_writer(&mut buf, &S165::sample()).unwrap();
    to_writer(&mut buf, &S166::sample()).unwrap();
    to_writer(&mut buf, &S167::sample()).unwrap();
    to_writer(&mut buf, &S168::sample()).unwrap();
    to_writer(&mut buf, &S169::sample()).unwrap();
    to_writer(&mut buf, &S170::sample()).unwrap();
    to_writer(&mut buf, &S171::sample()).unwrap();
    to_writer(&mut buf, &S172::sample()).unwrap();
    to_writer(&mut buf, &S173::sample()).unwrap();
    to_writer(&mut buf, &S174::sample()).unwrap();
    to_writer(&mut buf, &S175::sample()).unwrap();
    to_writer(&mut buf, &S176::sample()).unwrap();
    to_writer(&mut buf, &S177::sample()).unwrap();
    to_writer(&mut buf, &S178::sample()).unwrap();
    to_writer(&mut buf, &S179::sample()).unwrap();
    to_writer(&mut buf, &S180::sample()).unwrap();
    to_writer(&mut buf, &S181::sample()).unwrap();
    to_writer(&mut buf, &S182::sample()).unwrap();
    to_writer(&mut buf, &S183::sample()).unwrap();
    to_writer(&mut buf, &S184::sample()).unwrap();
    to_writer(&mut buf, &S185::sample()).unwrap();
    to_writer(&mut buf, &S186::sample()).unwrap();
    to_writer(&mut buf, &S187::sample()).unwrap();
    to_writer(&mut buf, &S188::sample()).unwrap();
    to_writer(&mut buf, &S189::sample()).unwrap();
    to_writer(&mut buf, &S190::sample()).unwrap();
    to_writer(&mut buf, &S191::sample()).unwrap();
    to_writer(&mut buf, &S192::sample()).unwrap();
    to_writer(&mut buf, &S193::sample()).unwrap();
    to_writer(&mut buf, &S194::sample()).unwrap();
    to_writer(&mut buf, &S195::sample()).unwrap();
    to_writer(&mut buf, &S196::sample()).unwrap();
    to_writer(&mut buf, &S197::sample()).unwrap();
    to_writer(&mut buf, &S198::sample()).unwrap();
    to_writer(&mut buf, &S199::sample()).unwrap();
    std::hint::black_box(buf);
}
